cache:
  directories:
    - $HOME/.m2

language: java

jdk:
  - openjdk8

script:
  - mvn cobertura:cobertura

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master

after_success:
  - bash <(curl -s https://codecov.io/bash)
